@startuml

title __APP's Class Diagram__\n

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.Connect {
          {static} + PATTERN_QUERY : String[]
          {static} + emails : List<String>
          + indeks : int
          + movies : ArrayList<ArrayList<String>>
          + moviesTimeStart : ArrayList<String>
          {static} + passwd : String
          {static} + query : String
          {static} + tableName : String
          ~ imie : String
          {static} ~ jdbcCollumn : List<String>
          ~ stmt : Statement
          - connection : Connection
          - dbname : String
          - driver : String
          - host : String
          - pass : String
          - port : String
          - queryPrice : String
          - tablesName : List<String>
          - url : String
          - user : String
          + Connect()
          + addMovieToBase()
          + close()
          + getConnection()
          {static} + getPasswd()
          + getQueryPrice()
          + getTables()
          + getTablesName()
          + gettingDataInputData()
          + idGenerator()
          + makeConnection()
          + mkQuery()
          + queryGetTime()
          + queryMovies()
          {static} + setPasswd()
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.CreateTicket {
          {static} + createTicket()
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.Main {
          {static} + connect : Connect
          {static} - scene : Scene
          + Main()
          + init()
          {static} + main()
          {static} + setRoot()
          + start()
          + stop()
          {static} - loadFXML()
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.SendEmail {
          {static} + sendEmail()
      }
    }
  }
  

  pl.cinema.app.Main -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
