@startuml

title __JAVA-II-CINEMA-PROJECT's Class Diagram__\n

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.Connect {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.CreateTicket {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.Main {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.app {
      class pl.cinema.app.SendEmail {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.AddMovieController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.ChefPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.CinemaDescriptionPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.ClientDataPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.EmployeePaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.LoginPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.MainPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.PricePaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.RepertoirePaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.controller {
      class pl.cinema.controller.ReservationPaneController {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.model {
      class pl.cinema.model.Customer {
      }
    }
  }
  

  namespace  {
    namespace l.cinema.model {
      class pl.cinema.model.Ticket {
      }
    }
  }
  

  pl.cinema.app.Main -up-|> javafx.application.Application


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
